parameters:
  - name: reviewTimeBudget
    type: string
    default: "20"
  - name: dryRun
    type: boolean
    default: false
  - name: ignoreFiles
    type: object
    default:
      - docs/**
      - "**/*.md"

stages:
  - stage: CodexReview
    displayName: Codex Review
    jobs:
      - job: Review
        displayName: Run Codex Review
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: NodeTool@0
            displayName: Use Node.js

          - script: |
              set -euxo pipefail
              npm install -g pnpm@8
              pnpm install --frozen-lockfile=false
            displayName: Install dependencies

          - script: |
              set -euxo pipefail
              ARGS=""
              if [ "$REVIEW_DRY_RUN" = "true" ]; then
                ARGS="$ARGS --dry-run"
              fi
              npx @charlietango/az-pipeline-codex-review-agent@${{ parameters.packageVersion }} \
                --review-time-budget "$REVIEW_TIME_BUDGET" \
                --ignore-files '${{ join(parameters.ignoreFiles, "' --ignore-files '") }}' \
                $ARGS
            displayName: Run Codex review
            env:
              OPENAI_API_KEY: $(OPENAI_API_KEY)
              AZURE_DEVOPS_PAT: $(System.AccessToken)
              REVIEW_TIME_BUDGET: ${{ parameters.reviewTimeBudget }}
              REVIEW_DRY_RUN: ${{ parameters.dryRun }}
